### ISSUE TITLE
CDH Agent虚拟机模板问题请教

### ISSUE THREAD

**Issue by geosmart** [wuranbo/gist#1]
看到您记录的CDH的表结构，向您请教个问题

* 问题描述：CDH Manager安装配置好一台Agent机器A（VM虚拟机）后，如果以A复制出B，在集群中B与A会冲突，每次Host Inspector只能检测到一个

* 问题定位：判断为SCM库中HOSTS表的HOST_IDENTIFIER字段冲突导致

* 解决思路：ClouderaManager是根据什么自动生成HOST_IDENTIFIER的？ 如何复制VM虚拟机才能不冲突？ 

请指教，非常感谢！

**Comment by geosmart** [comment]
已解决了，记录如下：

*	问题描述：CDH Manager安装配置好一台Agent机器A（VM虚拟机）后，如果以A复制出B，在集群中B与A会冲突，每次Host Inspector只能检测到一个
*	问题定位：判断为SCM库中HOSTS表的HOST_IDENTIFIER字段冲突导致
*	解决思路：ClouderaManager是根据什么自动生成HOST_IDENTIFIER的？ 如何复制VM虚拟机才能不冲突？
* 问题解决：由于在复制cm-5.4.7到agent之前启动了cloudera-scm-agent，在/opt/cm-5.4.7/lib/cloudera-scm-agent中生成response.avro和uuid两个文件，cloudera的HOST_IDENTIFIER读取的就是uuid文件的文本，停止agent>删除response.avro和uuid>启动agent，问题解决

**Comment by wuranbo** [comment]
哇咔咔。好赞。刚看到。我cloudera用的也不熟。就是要做一个跟cloudera类似的东西，所以调研了下他的实现。

**Comment by geosmart** [comment]
66666，自己实现一套CDH啊，搞的怎么样啊？
github上也有个国内开源的[easyhadoop](https://github.com/xianglei/easyhadoop)，不知道怎么样，没用过

**Comment by wuranbo** [comment]
多谢@geosmart 提醒，这还真不了解。因为我们不是要做成cloudera那样，是要管理公司自己的系统，所以也不会那么通用太多能参考。哈~
